### ISSUE TITLE
Finding all Values for Config.js

### ISSUE THREAD

**Issue by mrappard** [Azure-Samples/active-directory-verifiable-credentials-node#14]
For the Tutorial at (https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/verifiable-credentials-configure-verifier)

In the section where you update the app setting it's written for DOTNET not NODEJS. 

That is fine, but that variables required are different with NodeJS giving variable that aren't specified. I've bolded them, please advise where to find variable or update code not to require them.

Config.js NODEJS {
    "azTenantId": "<YOUR-AAD-TENANDID>",
    "azClientId": "<YOUR-AAD-CLIENTID-FOR-API-ACCESS>",
    "azClientSecret": "<YOUR-AAD-CLIENTSECRET-FOR-API-ACCESS>",
    "azCertificateName":  "<YOUR-AAD-CERTNAME>",
    **"azCertThumbprint":  "<YOUR-AAD-CERTTHUMBPRINT>",**
    **"azCertificatePrivateKeyLocation":  "<YOUR-AAD-CERTLOCATION>",**
    "CredentialManifest": "<YOUR-MANIFEST-URL>",
    "IssuerAuthority": "<YOUR-did:ion>",
    "VerifierAuthority": "<VCs-did:ion>"
}

appsettings.json DOTNET
{
    "Endpoint": "https://beta.did.msidentity.com/v1.0/{0}/verifiablecredentials/request",
    "VCServiceScope": "3db474b9-6a0c-4840-96ac-1fceb342124f/.default",
    "Instance": "https://login.microsoftonline.com/{0}",

    "TenantId": "YOURTENANTID",
    "ClientId": "APPLICATION CLIENT ID",
    "ClientSecret": "[client secret or instead use the prefered certificate in the next entry]",
    "CertificateName": "[Or instead of client secret: Enter here the name of a certificate (from the user cert store) as registered with your application]",
    "IssuerAuthority": "YOUR VC SERVICE DID",
    "VerifierAuthority": "YOUR VC SERVICE DID",
    "CredentialManifest": "THE CREDENTIAL URL FROM THE VC PORTAL"
  }

**Comment by cljung** [comment]
@mrappard - Not quite sure I follow you when you say the values are different. But if you do not want to use a certificate based auth with the node.js sample, just set the azCertificateName to an empty string in config.json

**Comment by cljung** [comment]
The cert thumbprint and location will be part of the output when running .\Configure.ps or ./Configure.sh.  
https://github.com/Azure-Samples/active-directory-verifiable-credentials-node/tree/main/1-node-api-idtokenhint/AppCreationScripts#option-3---specify-type-of-app-credentials
